”€
server.port=8081

”€
app.base-url=http://localhost:8081

”€
spring.datasource.url=jdbc:mysql://localhost:3306/railflow1
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Huzshahul@05

”€
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
”€
jwt.secret=ThisIsAVeryLongAndSecureSecretKeyForRailFlowAppThatIsAtLeast256BitsLong
jwt.expiration=86400000


